local colors = {
-- PATCH_OPEN
Normal = {fg = "#E2E2E2"},
Function = {link = "Normal"},
Identifier = {link = "Normal"},
Character = {fg = "#FBBC3F"},
ColorColumn = {bg = "#575757"},
Comment = {fg = "#848484", italic = true},
Constant = {fg = "#F59DD4"},
Boolean = {link = "Constant"},
["@constant.builtin"] = {link = "Constant"},
Cursor = {bg = "#FFFFFF"},
CursorIM = {link = "Cursor"},
CursorLine = {bg = "#1B1B1B"},
CursorLineNr = {fg = "#BFBF00", bg = "#1B291A", bold = true},
DapBreakpoint = {fg = "#FE0008", bg = "#262626"},
DapBreakpointCondition = {fg = "#FF5717", bg = "#262626"},
DapBreakpointRejected = {fg = "#ABABAB", bg = "#262626"},
DapLogPoint = {fg = "#429EBE", bg = "#262626"},
DapStopped = {fg = "#FFFFFF", bg = "#262626"},
DapStoppedLine = {bg = "#1D361B"},
Delimiter = {fg = "#ABABAB"},
DiagnosticNumError = {bg = "#860002"},
DiagnosticNumInfo = {},
DiagnosticNumHint = {link = "DiagnosticNumInfo"},
DiagnosticNumWarn = {bg = "#B06000"},
DiagnosticSignError = {fg = "#D80005", bg = "#262626"},
DiagnosticSignInfo = {fg = "#5FD7FF", bg = "#262626"},
DiagnosticSignHint = {link = "DiagnosticSignInfo"},
DiagnosticSignWarn = {fg = "#FE8500", bg = "#262626"},
DiffAdd = {fg = "#6CDE6D", bg = "#005B03"},
DiffChange = {fg = "#C6C6EF", bg = "#00003C"},
DiffDelete = {fg = "#F9A1A1", bg = "#5C0001"},
DiffSignAdd = {fg = "#00AB0B", bg = "#262626"},
GitGutterAdd = {link = "DiffSignAdd"},
SignifySignAdd = {link = "DiffSignAdd"},
DiffSignChange = {fg = "#CDCD20", bg = "#262626"},
GitGutterChange = {link = "DiffSignChange"},
SignifySignChange = {link = "DiffSignChange"},
DiffSignDelete = {fg = "#FF282A", bg = "#262626"},
GitGutterDelete = {link = "DiffSignDelete"},
SignifySignDelete = {link = "DiffSignDelete"},
DiffText = {fg = "#75D9D9", bg = "#005F5F"},
Directory = {fg = "#00AFFF"},
Error = {fg = "#E2E2E2", bg = "#8F0002"},
ErrorMsg = {fg = "#E2E2E2", bg = "#AE0003"},
Exception = {fg = "#3491FF", bold = true},
FloatBorder = {fg = "#8A7262", bg = "#392E27"},
FoldColumn = {fg = "#5FD7FF", bg = "#1B1B1B"},
Folded = {fg = "#5FD7FF", bg = "#00003C"},
TSNamespace = {link = "Identifier"},
IncSearch = {fg = "#FEFF00", bg = "#008806"},
IndentGuidesEven = {fg = "#5E5E5E"},
IndentGuidesOdd = {fg = "#474747"},
LineNr = {fg = "#6A6A6A", bg = "#262626"},
SignColumn = {link = "LineNr"},
MatchParen = {bg = "#575757"},
ModeMsg = {fg = "#D6AF00"},
MoreMsg = {fg = "#D6AF00"},
NonText = {fg = "#525252"},
NormalFloat = {fg = "#E2E2E2", bg = "#392E27"},
DiagnosticFloatingError = {link = "NormalFloat"},
DiagnosticFloatingHint = {link = "NormalFloat"},
DiagnosticFloatingInfo = {link = "NormalFloat"},
DiagnosticFloatingWarn = {link = "NormalFloat"},
Number = {fg = "#CC92FF"},
Float = {link = "Number"},
Operator = {fg = "#97F2F0"},
["@constructor"] = {link = "Operator"},
["@function.builtin"] = {link = "Operator"},
Pmenu = {fg = "#E2E2E2", bg = "#4C3727"},
PmenuSbar = {bg = "#616161"},
PmenuSel = {fg = "#E2E2E2", bg = "#775841"},
PmenuThumb = {bg = "#CCCCCC"},
PreProc = {fg = "#96D93E"},
Question = {fg = "#D6AF00"},
Search = {fg = "#FEFF00", bg = "#575757"},
LspReferenceRead = {link = "Search"},
LspReferenceText = {link = "Search"},
LspReferenceWrite = {link = "Search"},
Special = {fg = "#D75C86"},
SpecialHint = {fg = "#525252", italic = true},
SpecialKey = {fg = "#D75C86"},
SpellBad = {sp = "#ff0000", undercurl = true},
SpellCap = {sp = "#eecc00", undercurl = true},
SpellLocal = {link = "SpellCap"},
SpellRare = {link = "SpellCap"},
Statement = {fg = "#699EF6"},
StatusLine = {fg = "#919191", bg = "#3B3B3B"},
StatusLineNC = {fg = "#5E5E5E", bg = "#1B1B1B"},
String = {fg = "#F29274"},
TabLine = {fg = "#989898", bg = "#282828"},
TabLineFill = {bg = "#262626"},
TabLineSel = {fg = "#E2E2E2", bg = "#4E4E4E"},
Title = {fg = "#D6AF00", bold = true},
Todo = {fg = "#E0B700", bold = true},
Type = {fg = "#F8DC64"},
VertSplit = {fg = "#AAAA55"},
Visual = {bg = "#404040"},
VisualNOS = {bg = "#404040"},
WarningMsg = {fg = "#E5E5E5", bg = "#D86000", bold = true},
Whitespace = {fg = "#525252"},
helpHyperTextJump = {fg = "#7FAFFF", underline = true},
["@variable.builtin"] = {fg = "#E991B0"},
-- PATCH_CLOSE
}

vim.cmd([[highlight clear]])
vim.cmd([[set t_Co=256]])
vim.cmd([[let g:colors_name='meteor-nvim']])

-- apply highlight groups
for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end
